version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=finalproject
      - POSTGRES_PASSWORD=finalproject
      - POSTGRES_DB=finalproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finalproject"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=finalproject
      - DB_USER=finalproject
      - DB_PASS=finalproject
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "80:80"
    environment:
      - API_HOST=backend
      - PORT=8080

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  db:
    driver: local




