version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=finalproject
      - POSTGRES_PASSWORD=finalproject
      - POSTGRES_DB=finalproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finalproject"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
